### ISSUE TITLE
New Query opens multiple windows

### ISSUE THREAD

**Issue by dzsquared** [dzsquared/query-editor-boost#22]
References https://github.com/microsoft/azuredatastudio/issues/10725

**Comment by dzsquared** [comment]
**Thank you for raising an issue for query-editor-boost**

This isn't my full time job, but I hope to get back to you soon. I really appreciate feedback on issues and new feature requests!

**Comment by Remko1981** [comment]
I wanted to comment that i experience the same issue. I also could not close the window anymore. Therefore i removed the CTRL + N shortcut for query editor boost. 

Run current query section and use database work like a charm. Thanks for your work!

**Comment by dzsquared** [comment]
@Remko1981  can we confirm which version of Query Editor Boost you are using?  v0.4.0 is currently in the marketplace but v0.4.1 is the latest.  I believe v0.4.1 will resolve the issue and it should be hitting the marketplace soon for convenience, but you can grab it here: https://github.com/dzsquared/query-editor-boost/releases/tag/0.4.1

thank you!
